# As new .c files are added, make a rule as per the standard below for them, then add the compilation
# instructions to the "all" segment

all: 
	gcc hello.c -o hello

hello: hello.c
	gcc hello.c -o hello

